version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=m3atyy@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - web
    restart: unless-stopped

  api:
    image: docker.io/rykovs/ym-sucks:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`ym-sucks.da-maltsev.ru`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    networks:
      - web
    restart: unless-stopped

  ui:
    image: docker.io/rykovs/ym-sucks-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`ym-sucks.da-maltsev.ru`) && PathPrefix(`/`)"
      - "traefik.http.services.ui.loadbalancer.server.port=3000"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge

volumes:
  letsencrypt: