FROM node:20.18.1-slim as builder

WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm ci
COPY ./frontend/ .
RUN npm run build

FROM node:20.18.1-slim

WORKDIR /app
COPY --from=builder /app/.output .output/
COPY ./frontend/package*.json ./

RUN npm ci --omit=dev && npm cache clean --force

ENV PORT=3000
EXPOSE 3000

USER node
CMD ["node", ".output/server/index.mjs"] 